### ISSUE TITLE
Support tags with pre-defined bounded values (i.e. enum tags)

### ISSUE THREAD

**Issue by iamdanfox** [palantir/metric-schema#394]
## What happened

I just defined the following metric using metric-schema but there were concerns at CR time that folks would misuse the `reason` tag and start putting unbounded stuff in it.

```yml
 task.noop:
  type: counter
  tags: [reason]
```

A possible solution on my end here is to just define an enum of possible reasons (see below), but I really don't want to maintain my own wrapper around the nice metric-schema generated class. 

```java
public enum TaskNoOpReason {
    FAILURE_TO_ACQUIRE_LOCK,
    NO_LONGER_IN_THE_STORE,
    MISMATCHED_PROCESSING_TIME,
    UNSUPPORTED_CANDIDATE_TYPE
}
```

## Proposal

So the proposal is: what about extending the metric-schema yml format so that I could define the known options upfront somehow, e.g.:

```yml
     task.noop:
        type: counter
        tags: 
        - reason: [failure-to-acquire-lock, no-longer-in-the-store, mismatched-processing-time, unsupported-candidate-type]
```

(I'd still want to support the existing syntax to avoid imposing this on everyone)
